updated cicd aws

diff --git a/.github/workflows/aws_ci_cd.yml b/.github/workflows/aws_ci_cd.yml
--- a/.github/workflows/aws_ci_cd.yml
+++ b/.github/workflows/aws_ci_cd.yml
@@ -63,7 +63,7 @@ jobs:
             -d '{"features":[5.1,3.5,1.4,0.2]}'
       - run: docker rm -f test_container
 
-  deploy_aws:
+    deploy_aws:
     runs-on: ubuntu-latest
     needs: smoke-test
     steps:
@@ -105,10 +105,24 @@ jobs:
             --service mlops-service \
             --force-new-deployment
 
-      - name: Wait for task to start
+      - name: Wait for ECS task to be running
         run: |
-          echo "⏳ Waiting 60s for ECS task to start..."
-          sleep 60
+          echo "⏳ Waiting for ECS task to start..."
+          sleep 20
+          TASK_ARN=$(aws ecs list-tasks \
+            --cluster mlops-cluster \
+            --service-name mlops-service \
+            --query "taskArns[0]" --output text)
+
+          if [ "$TASK_ARN" == "None" ] || [ -z "$TASK_ARN" ]; then
+            echo "❌ No ECS task found for service mlops-service"
+            exit 1
+          fi
+
+          aws ecs wait tasks-running \
+            --cluster mlops-cluster \
+            --tasks $TASK_ARN
+          echo "✅ Task is now running: $TASK_ARN"
 
       - name: Get Public IP of ECS Task
         run: |
@@ -122,6 +136,11 @@ jobs:
             --tasks $TASK_ARN \
             --query "tasks[0].attachments[0].details[?name=='publicIPv4Address'].value" \
             --output text)
+
+          if [ -z "$PUBLIC_IP" ]; then
+            echo "❌ Could not fetch Public IP."
+            exit 1
+          fi
 
           echo "✅ ECS Task Public IP: $PUBLIC_IP"
           echo "🌍 Test your API at: http://$PUBLIC_IP:8000/predict"
